version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: service_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - 5432:5432
    volumes:
      - ./entrypoints/load-extensions.sh:/docker-entrypoint-initdb.d/load-extensions.sh
